class BlogStructurerAgent:
    def build(self, title, image_url, summary, background, terms, link):
        return f"""

![Image]({image_url})



## 🔹 Summary:
{summary}

[Read full article]({link})

## 🔹 Background:
{background}

## 🔹 Key Terms Explained:
{terms}

---
*Generated by Auto News Agents*
"""