runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

env_variables:
  GNEWS_API_KEY: "bea50cafacc00510210b2a5c4f314578"
  UNSPLASH_API_KEY: "conmMZ5yKGtgPZJMNCkyhLi7QqLpLWbUlF39A5ygm9k"
  GEMINI_API_KEY: "AIzaSyApU4_62je4aUfngLiOdwlAYpDMlmSSegA"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto